version: "2"
services:
  genie:
    image: netflixoss/genie-app:3.3.20-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - genie-hadoop-prod
      - genie-hadoop-test
      - genie-apache
    tty: true
    container_name: genie_demo_app_3.3.20-SNAPSHOT
  genie-apache:
    image: netflixoss/genie-demo-apache:3.3.20-SNAPSHOT
    tty: true
    container_name: genie_demo_apache_3.3.20-SNAPSHOT
  genie-client:
    image: netflixoss/genie-demo-client:3.3.20-SNAPSHOT
    depends_on:
      - genie
    tty: true
    container_name: genie_demo_client_3.3.20-SNAPSHOT
  genie-hadoop-prod:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
    tty: true
    container_name: genie_demo_hadoop_prod_3.3.20-SNAPSHOT
  genie-hadoop-test:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19889:19888"
      - "50071:50070"
      - "50076:50075"
      - "8089:8088"
    tty: true
    container_name: genie_demo_hadoop_test_3.3.20-SNAPSHOT
